# Generated by Django 3.0.5 on 2020-04-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200424_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
